# Generated by Django 5.1.1 on 2024-11-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_libro_fecha_arriendo_alter_libro_arrendador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha_arriendo',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='fecha_arriendo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
