# Generated by Django 5.1.1 on 2024-11-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_libro_fecha_arriendo_arriendo_fecha_arriendo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_arriendo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
