# Generated by Django 5.1.1 on 2024-11-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_arriendo_fecha_alter_arriendo_fecha_arriendo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_arriendo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
